### ISSUE TITLE
systemd-journal 100% CPU

### ISSUE THREAD

**Issue by scegg** [snapcore/classic-snap#12]
I'm using Ubuntu Core on Raspberry Pi 3B and classic beta.

I found systemd-journal eats 100% cpu in top.

No more operating done after install classic.

Many lines are like these:

Jun 24 17:31:19 localhost.localdomain audit[1481]: AVC apparmor="ALLOWED" operation="recvmsg" profile="snap.classic.classic//null-/usr/bin/systemd-run//null-/usr/sbin/chr
Jun 24 17:31:19 localhost.localdomain audit[1481]: AVC apparmor="ALLOWED" operation="getpeername" profile="snap.classic.classic//null-/usr/bin/systemd-run//null-/usr/sbin
Jun 24 17:31:19 localhost.localdomain audit[1481]: AVC apparmor="ALLOWED" operation="sendmsg" profile="snap.classic.classic//null-/usr/bin/systemd-run//null-/usr/sbin/chr
Jun 24 17:31:19 localhost.localdomain audit[1481]: AVC apparmor="ALLOWED" operation="recvmsg" profile="snap.classic.classic//null-/usr/bin/systemd-run//null-/usr/sbin/chr
Jun 24 17:31:19 localhost.localdomain audit[1481]: AVC apparmor="ALLOWED" operation="recvmsg" profile="snap.classic.classic//null-/usr/bin/systemd-run//null-/usr/sbin/chr
Jun 24 17:31:19 localhost.localdomain audit[1482]: AVC apparmor="ALLOWED" operation="getpeername" profile="snap.classic.classic//null-/usr/bin/systemd-run//null-/usr/sbin
Jun 24 17:31:19 localhost.localdomain audit[1482]: AVC apparmor="ALLOWED" operation="sendmsg" profile="snap.classic.classic//null-/usr/bin/systemd-run//null-/usr/sbin/chr
Jun 24 17:31:20 localhost.localdomain audit[1481]: AVC apparmor="ALLOWED" operation="recvmsg" profile="snap.classic.classic//null-/usr/bin/systemd-run//null-/usr/sbin/chr
Jun 24 17:31:20 localhost.localdomain audit[1481]: AVC apparmor="ALLOWED" operation="recvmsg" profile="snap.classic.classic//null-/usr/bin/systemd-run//null-/usr/sbin/chr
Jun 24 17:31:20 localhost.localdomain audit[1482]: AVC apparmor="ALLOWED" operation="sendmsg" profile="snap.classic.classic//null-/usr/bin/systemd-run//null-/usr/sbin/chr
Jun 24 17:31:20 localhost.localdomain audit[1481]: AVC apparmor="ALLOWED" operation="recvmsg" profile="snap.classic.classic//null-/usr/bin/systemd-run//null-/usr/sbin/chr
Jun 24 17:31:20 localhost.localdomain audit[1481]: AVC apparmor="ALLOWED" operation="recvmsg" profile="snap.classic.classic//null-/usr/bin/systemd-run//null-/usr/sbin/chr
Jun 24 17:31:20 localhost.localdomain audit[1482]: AVC apparmor="ALLOWED" operation="sendmsg" profile="snap.classic.classic//null-/usr/bin/systemd-run//null-/usr/sbin/chr
Jun 24 17:31:20 localhost.localdomain audit[1482]: AVC apparmor="ALLOWED" operation="open" profile="snap.classic.classic//null-/usr/bin/systemd-run//null-/usr/sbin/chroot
J

Too many write to SD card.

**Comment by jdstrand** [comment]
It seems like the classic snap does not have the classic-support interface connected. What is the output of `snap interfaces`?

**Comment by scegg** [comment]
@jdstrand 
Thanks for your reply. This is the output you requested.

Slot                      Plug
:account-control          -
:alsa                     -
:autopilot-introspection  -
:bluetooth-control        -
:browser-support          -
:camera                   -
:classic-support          -
:core-support             core:core-support-plug
:dcdbas-control           -
:docker-support           -
:firewall-control         -
:framebuffer              -
:fuse-support             -
:hardware-observe         -
:hardware-random-control  -
:hardware-random-observe  -
:home                     -
:io-ports-control         -
:joystick                 -
:kernel-module-control    -
:kubernetes-support       -
:log-observe              -
:lxd-support              -
:mount-observe            -
:netlink-audit            -
:netlink-connector        -
:network                  -
:network-bind             -
:network-control          -
:network-observe          -
:network-setup-control    -
:network-setup-observe    -
:opengl                   -
:openvswitch-support      -
:physical-memory-control  -
:physical-memory-observe  -
:ppp                      -
:process-control          -
:raw-usb                  -
:removable-media          -
:shutdown                 -
:snapd-control            -
:system-observe           -
:system-trace             -
:time-control             -
:timeserver-control       -
:timezone-control         -
:tpm                      -
:uhid                     -

**Comment by ogra1** [comment]
what is the output of:

snap info classic

you should be at least on revision 24, if not, please run "snap refresh --devmode --beta classic", due to the fact that devmode snaps do not auto-update you might be on an old version that does not have the fix yet.

**Comment by scegg** [comment]
Maybe this is the problem.

name:      classic
summary:   "Classic environment"
publisher: canonical
contact:   snappy-canonical-storeaccount@canonical.com
description: |
  Classic environment
commands:
  - classic
  - classic.create
  - classic.reset
tracking:    beta
installed:   16.04 (17) 4kB devmode
refreshed:   2016-10-05 08:18:36 +0000 UTC
channels:
  stable:    –
  candidate: –
  beta:      16.04 (26) 4kB devmode
  edge:      16.04 (26) 4kB devmode

Now I upgraded it to 26. Hope this is fixed.

**Comment by jdstrand** [comment]
Ah, yes, devmode snaps don't auto-refresh yet and r17 didn't plugs classic-support. Thanks for getting back to us! :)
