### ISSUE TITLE
Feature Request:

### ISSUE THREAD

**Issue by scegg** [snapcore/classic-snap#13]
Is that possible to make something running while start classic?
like code in rc.local, or somewhere else.

I found that I cannot enable a service though systemctl in classic. Program cannot start as a service way.

Thanks.

**Comment by dankegel** [comment]
You can't start a systemctl service inside classic, as that's implemented with chroot; see https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1594738
so whatever daemon you wanted to start, you need to start by hand without systemd.
(Alternately, maybe you could use a container.)

For instance, create a script that runs the startup job, then starts an interactive shell.
Then when you run 'sudo classic', pass the path to this script, e.g. create blah.sh containing

```
#!/bin/sh
sudo swapon /var/tmp/swapfile
exec bash
```

then do
```
chmod +x blah.sh
sudo classic ./blah.sh
```
it'll activate swap, then run an interactive shell.

**Comment by scegg** [comment]
Thanks for your information
