### ISSUE TITLE
Classic Dimension for Ubuntu Core 20

### ISSUE THREAD

**Issue by howardcochran** [snapcore/classic-snap#34]
Hello.

We are preparing to migrate from UC16 to UC20 for our embedded devices. As we do most development of our code in-device, this means we require a Ubuntu 20-based classic dimension.  However it appears that the latest available is based on UC18.

**Comment by anonymouse64** [comment]
Hi, the classic snap has been deprecated and is no longer supported on UC18 or on UC20. For development on such devices, we recommend using the LXD snap (which is strict) to create a classic Ubuntu container based on 18.04 or 20.04, you can do so with these commands:

```
sudo snap install lxd 
sudo lxd init --auto
sudo lxc launch ubuntu:20.04 -c dev
sudo lxc shell dev
```
