### ISSUE TITLE
Using ZFS outside classic

### ISSUE THREAD

**Issue by Darkade** [snapcore/classic-snap#6]
I used classic to `sudo apt install zfs` and it worked but I would like to use it outside of classic. I know it's listed right under **restrictions** I can't do that. But could you point me in the right direction?

I had to go outside of classic to activate the zfs kernel modules, and that's expected, I guess. So I think the kernel can run ZFS outside of classic. Could it be just a matter of making a snap of the zpool command?

Thanks

**Comment by rinurinu** [comment]
I would like to do something similar, [using mdadm outside of classic](http://askubuntu.com/questions/888404/ubuntu-core-with-raid-1). Did you find a solution to this yet?
